config/routes.rb
  get "users/:username/private-messages/:filter" => "user_actions#private_messages", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username" => "users#show", as: 'user', constraints: {username: USERNAME_ROUTE_FORMAT}
  put "users/:username" => "users#update", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/preferences" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}, as: :email_preferences
  get "users/:username/preferences/email" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}
  put "users/:username/preferences/email" => "users#change_email", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/preferences/about-me" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/preferences/badge_title" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}
  put "users/:username/preferences/badge_title" => "users#badge_title", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/preferences/username" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}
  put "users/:username/preferences/username" => "users#username", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/avatar(/:size)" => "users#avatar", constraints: {username: USERNAME_ROUTE_FORMAT} # LEGACY ROUTE
  post "users/:username/preferences/avatar" => "users#upload_avatar", constraints: {username: USERNAME_ROUTE_FORMAT} # LEGACY ROUTE
  post "users/:username/preferences/user_image" => "users#upload_user_image", constraints: {username: USERNAME_ROUTE_FORMAT}
  delete "users/:username/preferences/user_image" => "users#destroy_user_image", constraints: {username: USERNAME_ROUTE_FORMAT}
  put "users/:username/preferences/avatar/pick" => "users#pick_avatar", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/invited" => "users#invited", constraints: {username: USERNAME_ROUTE_FORMAT}
  post "users/:username/send_activation_email" => "users#send_activation_email", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/activity" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/activity/:filter" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/badges" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
  delete "users/:username" => "users#destroy", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/by-external/:external_id" => "users#show"
  get "users/:username/flagged-posts" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/deleted-posts" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/badges_json" => "user_badges#username"

  post "user_avatar/:username/refresh_gravatar" => "user_avatars#refresh_gravatar"
  get "letter_avatar/:username/:size/:version.png" => "user_avatars#show_letter",
      format: false, constraints: {hostname: /[\w\.-]+/}
  get "user_avatar/:hostname/:username/:size/:version.png" => "user_avatars#show",
      format: false, constraints: {hostname: /[\w\.-]+/}


  get "uploads/:site/:id/:sha.:extension" => "uploads#show", constraints: {site: /\w+/, id: /\d+/, sha: /[a-z0-9]{15,16}/i, extension: /\w{2,}/}
  post "uploads" => "uploads#create"

  get "posts/by_number/:topic_id/:post_number" => "posts#by_number"
  get "posts/:id/reply-history" => "posts#reply_history"
  get "posts/:username/deleted" => "posts#deleted_posts", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "posts/:username/flagged" => "posts#flagged_posts", constraints: {username: USERNAME_ROUTE_FORMAT}

  resources :groups do
    get 'members'
    get 'posts'
    get 'counts'
  end

  resources :posts do
    put "bookmark"
    put "wiki"
    get "replies"
    get "revisions/:revision" => "posts#revisions"
    put "recover"
    collection do
      delete "destroy_many"
    end
  end

  resources :notifications

  match "/auth/:provider/callback", to: "users/omniauth_callbacks#complete", via: [:get, :post]
  match "/auth/failure", to: "users/omniauth_callbacks#failure", via: [:get, :post]

  resources :clicks do
    collection do
      get "track"
    end
  end

  get "excerpt" => "excerpt#show"

  resources :post_actions do
    collection do
      get "users"
      post "defer_flags"
    end
  end
  resources :user_actions

  resources :badges, only: [:index]
  get "/badges/:id(/:slug)" => "badges#show"
  resources :user_badges, only: [:index, :create, :destroy]

  # We've renamed popular to latest. If people access it we want a permanent redirect.
  get "popular" => "list#popular_redirect"

  resources :categories, :except => :show
  get "category/:id/show" => "categories#show"
  post "category/uploads" => "categories#upload"
  post "category/:category_id/move" => "categories#move"
  get "category/:category.rss" => "list#category_feed", format: :rss
  get "category/:parent_category/:category.rss" => "list#category_feed", format: :rss
  get "category/:category" => "list#category_latest"
  get "category/:category/none" => "list#category_none_latest"
  get "category/:parent_category/:category" => "list#parent_category_category_latest"
  post "category/:category_id/notifications" => "categories#set_notifications"

  get "top" => "list#top"
  get "category/:category/l/top" => "list#category_top", as: "category_top"
  get "category/:category/none/l/top" => "list#category_none_top", as: "category_none_top"
  get "category/:parent_category/:category/l/top" => "list#parent_category_category_top", as: "parent_category_category_top"

  TopTopic.periods.each do |period|
    get "top/#{period}" => "list#top_#{period}"
    get "category/:category/l/top/#{period}" => "list#category_top_#{period}", as: "category_top_#{period}"
    get "category/:category/none/l/top/#{period}" => "list#category_none_top_#{period}", as: "category_none_top_#{period}"
    get "category/:parent_category/:category/l/top/#{period}" => "list#parent_category_category_top_#{period}", as: "parent_category_category_top_#{period}"
  end

  Discourse.anonymous_filters.each do |filter|
    get "#{filter}.rss" => "list##{filter}_feed", format: :rss
  end

  Discourse.filters.each do |filter|
    get "#{filter}" => "list##{filter}"
    get "category/:category/l/#{filter}" => "list#category_#{filter}", as: "category_#{filter}"
    get "category/:category/none/l/#{filter}" => "list#category_none_#{filter}", as: "category_none_#{filter}"
    get "category/:parent_category/:category/l/#{filter}" => "list#parent_category_category_#{filter}", as: "parent_category_category_#{filter}"
  end

  get "search" => "search#query"

  # Topics resource
  get "t/:id" => "topics#show"
  post "t" => "topics#create"
  put "t/:id" => "topics#update"
  delete "t/:id" => "topics#destroy"
  put "topics/bulk"
  put "topics/reset-new" => 'topics#reset_new'
  post "topics/timings"
  get "topics/similar_to"
  get "topics/created-by/:username" => "list#topics_by", as: "topics_by", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "topics/private-messages/:username" => "list#private_messages", as: "topics_private_messages", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "topics/private-messages-sent/:username" => "list#private_messages_sent", as: "topics_private_messages_sent", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "topics/private-messages-unread/:username" => "list#private_messages_unread", as: "topics_private_messages_unread", constraints: {username: USERNAME_ROUTE_FORMAT}

  get 'embed/comments' => 'embed#comments'
  get 'embed/count' => 'embed#count'

  # Topic routes
  get "t/:slug/:topic_id/wordpress" => "topics#wordpress", constraints: {topic_id: /\d+/}
  get "t/:slug/:topic_id/moderator-liked" => "topics#moderator_liked", constraints: {topic_id: /\d+/}
  get "t/:topic_id/wordpress" => "topics#wordpress", constraints: {topic_id: /\d+/}
  get "t/:slug/:topic_id/summary" => "topics#show", defaults: {summary: true}, constraints: {topic_id: /\d+/, post_number: /\d+/}
  get "t/:topic_id/summary" => "topics#show", constraints: {topic_id: /\d+/, post_number: /\d+/}
  put "t/:slug/:topic_id" => "topics#update", constraints: {topic_id: /\d+/}
  put "t/:slug/:topic_id/star" => "topics#star", constraints: {topic_id: /\d+/}
  put "t/:topic_id/star" => "topics#star", constraints: {topic_id: /\d+/}
  put "t/:slug/:topic_id/status" => "topics#status", constraints: {topic_id: /\d+/}
  put "t/:topic_id/status" => "topics#status", constraints: {topic_id: /\d+/}
  put "t/:topic_id/clear-pin" => "topics#clear_pin", constraints: {topic_id: /\d+/}
  put "t/:topic_id/re-pin" => "topics#re_pin", constraints: {topic_id: /\d+/}
  put "t/:topic_id/mute" => "topics#mute", constraints: {topic_id: /\d+/}
  put "t/:topic_id/unmute" => "topics#unmute", constraints: {topic_id: /\d+/}
  put "t/:topic_id/autoclose" => "topics#autoclose", constraints: {topic_id: /\d+/}
  put "t/:topic_id/make-banner" => "topics#make_banner", constraints: {topic_id: /\d+/}
  put "t/:topic_id/remove-banner" => "topics#remove_banner", constraints: {topic_id: /\d+/}
  put "t/:topic_id/remove-allowed-user" => "topics#remove_allowed_user", constraints: {topic_id: /\d+/}
  put "t/:topic_id/recover" => "topics#recover", constraints: {topic_id: /\d+/}
  get "t/:topic_id/:post_number" => "topics#show", constraints: {topic_id: /\d+/, post_number: /\d+/}
  get "t/:topic_id/last" => "topics#show", post_number: 99999999, constraints: {topic_id: /\d+/}
  get "t/:slug/:topic_id.rss" => "topics#feed", format: :rss, constraints: {topic_id: /\d+/}
  get "t/:slug/:topic_id" => "topics#show", constraints: {topic_id: /\d+/}
  get "t/:slug/:topic_id/:post_number" => "topics#show", constraints: {topic_id: /\d+/, post_number: /\d+/}
  get "t/:slug/:topic_id/last" => "topics#show", post_number: 99999999, constraints: {topic_id: /\d+/}

app/helpers/topics_helper.rb
module TopicsHelper

  def render_topic_title(topic)
    link_to(topic.title,topic.relative_url)
  end

end

app/views/topics/plain.html.erb
<!DOCTYPE html>
<html lang="<%=SiteSetting.default_locale%>">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title><%= @topic_view.topic.title %></title>
  <%= crawlable_meta_data(title: @topic_view.title,
                          description: @topic_view.summary,
                          image: @topic_view.image_url) %>
</head>
<body>
<% @topic_view.posts.each do |post| %>
  <% if post.user %>
    <div class='creator'>
      <b><%= post.user.username_lower %></b> <%= "(#{post.user.name})" if SiteSetting.display_name_on_posts %> at <%= post.created_at.to_formatted_s(:long_ordinal) %> — #<%= post.post_number %>
    </div>
    <div class='post'>
      <% if post.hidden %>
        <%= t('flagging.user_must_edit').html_safe %>
      <% else %>
        <%= post.cooked.html_safe %>
      <% end %>
    </div>
    <hr/>
  <% end %>
<% end %>
<p>
  <% if @topic_view.prev_page %>
    <%= link_to t(:prev_page), @topic_view.prev_page_path, rel: 'prev' %>
  <% end %>
  <% if @topic_view.next_page %>
    <b><%= link_to t(:next_page), @topic_view.next_page_path, rel: 'next' %></b>
  <% end %>
</p>
</body>

app/views/topics/show.html.erb
<h2>
   <%= render_topic_title(@topic_view.topic) %>
</h2>
<% if c = @topic_view.topic.category %>
  <a href="/category/<%= c.slug.blank? ? c.id : c.slug %>"><%= c.name %></a>
<% end %>
<hr/>

<% @topic_view.posts.each do |post| %>
  <% if post.user %>
    <div class='creator'>
      <b><%= post.user.username_lower %></b> <%= "(#{post.user.name})" if SiteSetting.display_name_on_posts %> — <%= post.created_at.to_formatted_s(:iso8601) %> — #<%= post.post_number %>
    </div>
    <div class='post'>
      <% if post.hidden %>
        <%= t('flagging.user_must_edit').html_safe %>
      <% else %>
        <%= post.cooked.html_safe %>
      <% end %>
    </div>
    <hr/>
  <% end %>
<% end %>


<p>
  <% if @topic_view.prev_page %>
    <%= link_to t(:prev_page), @topic_view.prev_page_path, rel: 'prev' %>
  <% end %>
  <% if @topic_view.next_page %>
    <b><%= link_to t(:next_page), @topic_view.next_page_path, rel: 'next' %></b>
  <% end %>
</p>


<% content_for :head do %>
  <%= auto_discovery_link_tag(@topic_view, {action: :feed, slug: @topic_view.topic.slug, topic_id: @topic_view.topic.id}, title: t('rss_posts_in_topic', topic: @topic_view.title), type: 'application/rss+xml') %>
  <%= crawlable_meta_data(title: @topic_view.title,
                          description: @topic_view.summary,
                          image: @topic_view.image_url) %>
<% end %>

<% content_for(:title) { @topic_view.title } %>

app/views/topics/show.rss.erb
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <% topic_url = Discourse.base_url + @topic_view.relative_url %>
    <% lang = SiteSetting.find_by_name('default_locale').try(:value) %>
    <% site_email = SiteSetting.find_by_name('contact_email').try(:value) %>
    <title><%= @topic_view.title %></title>
    <link><%= topic_url %></link>
    <description><%= @topic_view.posts.first.raw %></description>
    <%= "<language>#{lang}</language>" if lang %>
    <lastBuildDate><%= @topic_view.topic.bumped_at.rfc2822 %></lastBuildDate>
    <category><%= @topic_view.topic.category.name %></category>
    <atom:link href="<%= topic_url %>.rss" rel="self" type="application/rss+xml" />
    <% @topic_view.recent_posts.each do |post| %>
      <% next unless post.user %>
      <item>
        <title><%= @topic_view.title %></title>
        <author><%= "no-reply@example.com (@#{post.user.username}#{" #{post.user.name}" if post.user.name.present?})" -%></author>
        <description><![CDATA[
          <% post_url = Discourse.base_url + post.url %>
          <p><%= t('author_wrote', author: link_to(post.user.name, user_url(post.user.username_lower))).html_safe %></p>
          <blockquote>
            <% if post.hidden %>
              <%= t('flagging.user_must_edit').html_safe %>
            <% else %>
              <%= post.cooked.html_safe %>
            <% end %>
          </blockquote>
          <p><%= link_to t('read_full_topic'), post_url %></p>
        ]]></description>
        <link><%= post_url %></link>
        <pubDate><%= post.created_at.rfc2822 %></pubDate>
        <guid isPermaLink="false">post-<%= post.topic_id %>-<%= post.post_number %></guid>
        <source url="<%= Discourse.base_url %><%= @topic_view.relative_url %>.rss"><%= @topic_view.title %></source>
      </item>
    <% end %>
  </channel>
</rss>