config/routes.rb
require "sidekiq/web"
require_dependency "scheduler/web"
require_dependency "admin_constraint"
require_dependency "staff_constraint"
require_dependency "homepage_constraint"
require_dependency "permalink_constraint"

# This used to be User#username_format, but that causes a preload of the User object
# and makes Guard not work properly.
USERNAME_ROUTE_FORMAT = /[A-Za-z0-9\_]+/ unless defined? USERNAME_ROUTE_FORMAT
BACKUP_ROUTE_FORMAT = /[a-zA-Z0-9\-_]*\d{4}(-\d{2}){2}-\d{6}\.tar\.gz/i unless defined? BACKUP_ROUTE_FORMAT

Discourse::Application.routes.draw do

  match "/404", to: "exceptions#not_found", via: [:get, :post]
  get "/404-body" => "exceptions#not_found_body"

  if Rails.env.development?
    mount Sidekiq::Web => "/sidekiq"
    mount Logster::Web => "/logs"
  else
    mount Sidekiq::Web => "/sidekiq", constraints: AdminConstraint.new
    mount Logster::Web => "/logs", constraints: AdminConstraint.new
  end

  resources :about

  get "site" => "site#index"

  resources :forums
  get "srv/status" => "forums#status"

  namespace :admin, constraints: StaffConstraint.new do
    get "" => "admin#index"

    resources :site_settings, constraints: AdminConstraint.new do
      collection do
        get "category/:id" => "site_settings#index"
      end
    end

    get "reports/:type" => "reports#show"

    resources :groups, constraints: AdminConstraint.new do
      collection do
        post "refresh_automatic_groups" => "groups#refresh_automatic_groups"
      end
      get "users"
    end

    resources :users, id: USERNAME_ROUTE_FORMAT do
      collection do
        get "list/:query" => "users#index"
        get "ip-info" => "users#ip_info"
        put "approve-bulk" => "users#approve_bulk"
        delete "reject-bulk" => "users#reject_bulk"
      end
      put "suspend"
      put "delete_all_posts"
      put "unsuspend"
      put "revoke_admin", constraints: AdminConstraint.new
      put "grant_admin", constraints: AdminConstraint.new
      post "generate_api_key", constraints: AdminConstraint.new
      delete "revoke_api_key", constraints: AdminConstraint.new
      put "revoke_moderation", constraints: AdminConstraint.new
      put "grant_moderation", constraints: AdminConstraint.new
      put "approve"
      post "refresh_browsers", constraints: AdminConstraint.new
      post "log_out", constraints: AdminConstraint.new
      put "activate"
      put "deactivate"
      put "block"
      put "unblock"
      put "trust_level"
      put "primary_group"
      post "groups" => "users#add_group", constraints: AdminConstraint.new
      delete "groups/:group_id" => "users#remove_group", constraints: AdminConstraint.new
      get "badges"
      get "leader_requirements"
    end

    resources :impersonate, constraints: AdminConstraint.new

    resources :email do
      collection do
        post "test"
        get "all"
        get "sent"
        get "skipped"
        get "preview-digest" => "email#preview_digest"
      end
    end

    scope "/logs" do
      resources :staff_action_logs,     only: [:index]
      resources :screened_emails,       only: [:index, :destroy]
      resources :screened_ip_addresses, only: [:index, :create, :update, :destroy]
      resources :screened_urls,         only: [:index]
    end

    get "/logs" => "staff_action_logs#index"

    get "customize" => "color_schemes#index", constraints: AdminConstraint.new
    get "customize/css_html" => "site_customizations#index", constraints: AdminConstraint.new
    get "customize/colors" => "color_schemes#index", constraints: AdminConstraint.new
    get "flags" => "flags#index"
    get "flags/:filter" => "flags#index"
    post "flags/agree/:id" => "flags#agree"
    post "flags/disagree/:id" => "flags#disagree"
    post "flags/defer/:id" => "flags#defer"
    resources :site_customizations, constraints: AdminConstraint.new
    resources :site_contents, constraints: AdminConstraint.new
    resources :site_content_types, constraints: AdminConstraint.new
    resources :color_schemes, constraints: AdminConstraint.new

    get "version_check" => "versions#show"

    resources :dashboard, only: [:index] do
      collection do
        get "problems"
      end
    end

    resources :api, only: [:index], constraints: AdminConstraint.new do
      collection do
        post "key" => "api#create_master_key"
        put "key" => "api#regenerate_key"
        delete "key" => "api#revoke_key"
      end
    end

    resources :backups, only: [:index, :create], constraints: AdminConstraint.new do
      member do
        get "" => "backups#show", constraints: { id: BACKUP_ROUTE_FORMAT }
        delete "" => "backups#destroy", constraints: { id: BACKUP_ROUTE_FORMAT }
        post "restore" => "backups#restore", constraints: { id: BACKUP_ROUTE_FORMAT }
      end
      collection do
        get "logs" => "backups#logs"
        get "status" => "backups#status"
        get "cancel" => "backups#cancel"
        get "rollback" => "backups#rollback"
        put "readonly" => "backups#readonly"
        get "upload" => "backups#check_backup_chunk"
        post "upload" => "backups#upload_backup_chunk"
      end
    end

    resources :export_csv, constraints: AdminConstraint.new do
      member do
        get "download" => "export_csv#download", constraints: { id: /[^\/]+/ }
      end
      collection do
        get "users" => "export_csv#export_user_list"
      end
    end

    resources :badges, constraints: AdminConstraint.new do
      collection do
        get "types" => "badges#badge_types"
        post "badge_groupings" => "badges#save_badge_groupings"
        post "preview" => "badges#preview"
      end
    end

    get "memory_stats"=> "diagnostics#memory_stats", constraints: AdminConstraint.new

  end # admin namespace

  get "email_preferences" => "email#preferences_redirect", :as => "email_preferences_redirect"
  get "email/unsubscribe/:key" => "email#unsubscribe", as: "email_unsubscribe"
  post "email/resubscribe/:key" => "email#resubscribe", as: "email_resubscribe"

  resources :session, id: USERNAME_ROUTE_FORMAT, only: [:create, :destroy] do
    collection do
      post "forgot_password"
    end
  end

  get "session/sso" => "session#sso"
  get "session/sso_login" => "session#sso_login"
  get "session/current" => "session#current"
  get "session/csrf" => "session#csrf"
  get "composer-messages" => "composer_messages#index"

  resources :users, except: [:show, :update, :destroy] do
    collection do
      get "check_username"
      get "is_local_username"
    end
  end

  resources :static
  post "login" => "static#enter"
  get "login" => "static#show", id: "login"
  get "faq" => "static#show", id: "faq"
  get "guidelines" => "static#show", id: "guidelines"
  get "tos" => "static#show", id: "tos"
  get "privacy" => "static#show", id: "privacy"
  get "signup" => "list#latest"

  post "users/read-faq" => "users#read_faq"
  get "users/search/users" => "users#search_users"
  get "users/password-reset/:token" => "users#password_reset"
  put "users/password-reset/:token" => "users#password_reset"
  get "users/activate-account/:token" => "users#activate_account"
  put "users/activate-account/:token" => "users#perform_account_activation", as: 'perform_activate_account'
  get "users/authorize-email/:token" => "users#authorize_email"
  get "users/hp" => "users#get_honeypot_value"
  get "my/*path", to: 'users#my_redirect'

  get "user_preferences" => "users#user_preferences_redirect"
  get "users/:username/private-messages" => "user_actions#private_messages", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/private-messages/:filter" => "user_actions#private_messages", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username" => "users#show", as: 'user', constraints: {username: USERNAME_ROUTE_FORMAT}
  put "users/:username" => "users#update", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/preferences" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}, as: :email_preferences
  get "users/:username/preferences/email" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}
  put "users/:username/preferences/email" => "users#change_email", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/preferences/about-me" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/preferences/badge_title" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}
  put "users/:username/preferences/badge_title" => "users#badge_title", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/preferences/username" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}
  put "users/:username/preferences/username" => "users#username", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/avatar(/:size)" => "users#avatar", constraints: {username: USERNAME_ROUTE_FORMAT} # LEGACY ROUTE
  post "users/:username/preferences/avatar" => "users#upload_avatar", constraints: {username: USERNAME_ROUTE_FORMAT} # LEGACY ROUTE
  post "users/:username/preferences/user_image" => "users#upload_user_image", constraints: {username: USERNAME_ROUTE_FORMAT}
  delete "users/:username/preferences/user_image" => "users#destroy_user_image", constraints: {username: USERNAME_ROUTE_FORMAT}
  put "users/:username/preferences/avatar/pick" => "users#pick_avatar", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/invited" => "users#invited", constraints: {username: USERNAME_ROUTE_FORMAT}
  post "users/:username/send_activation_email" => "users#send_activation_email", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/activity" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/activity/:filter" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "users/:username/badges" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}

app/views/layouts/_head.html.erb
<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="author" content="">
    <meta name="generator" content="Discourse <%= Discourse::VERSION::STRING %> - https://github.com/discourse/discourse version <%= Discourse.git_version %>">

    <link rel="icon" type="image/png" href="<%=SiteSetting.favicon_url%>">
    <link rel="apple-touch-icon" type="image/png" href="<%=SiteSetting.apple_touch_icon_url%>">

    <%= canonical_link_tag %>

    <%= render partial: "common/special_font_face" %>
    <%= render partial: "common/discourse_stylesheet" %>

    <%= discourse_csrf_tags %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= SiteSetting.default_locale %>" class="<%= html_classes %>">
  <head>
    <meta charset="utf-8">
    <title><%= content_for?(:title) ? yield(:title) + ' - ' + SiteSetting.title : SiteSetting.title %></title>
    <meta name="description" content="<%= @description_meta || SiteSetting.site_description %>">
    <%= render partial: "layouts/head" %>

    <%- if SiteSetting.enable_escaped_fragments? %>
    <meta name="fragment" content="!">
    <%- end %>

    <%= script "preload_store" %>
    <%= script "locales/#{I18n.locale}" %>
    <%= script "vendor" %>
    <%= script "application" %>
    <%- if staff? %>
      <%= script "admin"%>
    <%- end %>

    <%= raw SiteContent.content_for(:head) %>

    <%= render_google_universal_analytics_code %>

    <%= yield :head %>
  </head>

  <body>
    <noscript data-path="<%= request.env['PATH_INFO'] %>">
      <header class="d-header">
        <div class="container">
          <div class="contents">
            <div class="row">
              <div class="title span13">
                <a href="/"><img src="<%= (mobile_view? && SiteSetting.mobile_logo_url) || SiteSetting.logo_url %>" alt="<%=SiteSetting.title%>" id="site-logo"></a>
              </div>
            </div>
          </div>
        </div>
      </header>
      <div id="main-outlet" class="container">
        <!-- preload-content: -->
        <%= yield %>
        <!-- :preload-content -->
      </div>
      <footer id='noscript-footer'>
        <p><%= t 'powered_by_html' %></p>
      </footer>
    </noscript>

    <!--[if IE 9]><script type="text/javascript">ie = "new";</script><![endif]-->

    <%- unless customization_disabled? %>
      <%= SiteCustomization.custom_header(session[:preview_style], mobile_view? ? :mobile : :desktop) %>
    <%- end %>

    <section id='main'>
    </section>

    <% unless current_user %>
      <form id='hidden-login-form' method="post" action="<%=login_path%>" style="display: none;">
        <input name="username" type="text"     id="signin_username">
        <input name="password" type="password" id="signin_password">
        <input name="redirect" type="hidden">
        <input type="submit" id="signin-button" value="<%= t 'log_in' %>">
      </form>
    <% end %>

    <%- if @preloaded.present? %>
      <script>
      <%- @preloaded.each do |key, json| %>
        PreloadStore.store("<%= key %>",<%= escape_unicode(json) %>);
      <% end %>
      </script>
    <%- end %>

    <%= yield :data %>

    <footer id='bottom'><%= raw SiteContent.content_for(:bottom) %></footer>

    <%= render :partial => "common/discourse_javascript" %>

    <%= render_google_analytics_code %>
  </body>
</html>

app/views/layouts/crawler.html.erb
<!DOCTYPE html>
<html lang="<%= SiteSetting.default_locale %>">
  <head>
    <meta charset="utf-8">
    <title><%= content_for?(:title) ? yield(:title) + ' - ' + SiteSetting.title : SiteSetting.title %></title>
    <meta name="description" content="<%= @description_meta || SiteSetting.site_description %>">
    <%= render partial: "layouts/head" %>
    <%= raw SiteContent.content_for(:head) %>
    <%= yield :head %>
  </head>
  <body>
    <%- unless customization_disabled? %>
      <%= SiteCustomization.custom_header(session[:preview_style]) %>
    <%- end %>
    <header class="d-header">
      <div class="container">
        <div class="contents">
          <div class="row">
            <div class="title span13">
              <a href="/"><img src="<%=SiteSetting.logo_url%>" alt="<%=SiteSetting.title%>" id="site-logo"></a>
            </div>
          </div>
        </div>
      </div>
    </header>
    <div id="main-outlet" class="container">
      <!-- preload-content: -->
      <%= yield %>
      <!-- :preload-content -->
    </div>
    <footer id='bottom' class="container">
      <p><%= t 'powered_by_html' %></p>
    </footer>
  </body>
</html>

app/views/layouts/embed.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag 'embed' %>
    <%= javascript_include_tag 'break_string' %>

    <script>
      (function() {

        function postUp(msg) {
          if (parent) {
            parent.postMessage(msg, '<%= request.referer %>');
          }
        }

        function clickPostLink(e) {
          var postId = e.target.getAttribute('data-link-to-post');
          if (postId) {
            var postElement = document.getElementById('post-' + postId);
            if (postElement) {
              var rect = postElement.getBoundingClientRect();
              if (rect && rect.top) {
                postUp({type: 'discourse-scroll', top: rect.top});
                e.preventDefault();
                return false;
              }
            }
          }
        }

        window.onload = function() {
          // Send a post message with our loaded height
          postUp({type: 'discourse-resize', height: document['body'].offsetHeight});

          var postLinks = document.querySelectorAll("a[data-link-to-post]"),
              i;

          for (i=0; i<postLinks.length; i++) {
            postLinks[i].onclick = clickPostLink;
          }

          // Make sure all links in the iframe point to _blank
          var cookedLinks = document.querySelectorAll('.cooked a');
          for (i=0; i<cookedLinks.length; i++) {
            cookedLinks[i].target = "_blank";
          }

          // Adjust all names
          var names = document.querySelectorAll('.username a');
          for (i=0; i<names.length; i++) {
            var username = names[i].innerHTML;
            if (username) {
              names[i].innerHTML = new BreakString(username).break();
            }
          }

        };

      })();
    </script>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/no_js.html.erb
<!DOCTYPE html>
<html lang="<%= SiteSetting.default_locale %>">
  <head>
    <meta charset="utf-8">
    <title><%=SiteSetting.title%></title>
    <meta name="description" content="">
    <%= render partial: "layouts/head" %>
    <%= raw SiteContent.content_for(:head) %>
    <%= yield(:no_js_head) %>
  </head>
  <body>
    <%- unless customization_disabled? %>
      <%= SiteCustomization.custom_header(session[:preview_style]) %>
    <%- end %>
    <section id='main'>
      <header class="d-header">
        <div class="container">
          <div class="contents">
            <div class="row">
              <div class="title span13">
                <a href="/"><img src="<%=SiteSetting.logo_url%>" alt="<%=SiteSetting.title%>" id="site-logo"></a>
              </div>
              <% unless current_user %>
                <div class='panel clearfix'>
                  <a href="/login" class='btn btn-primary btn-small'><i class="fa fa-user"></i><%= I18n.t('log_in') %></a>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </header>
      <div id="main-outlet" class="container">
        <%= yield %>
      </div>
    </section>
    <footer id='bottom' class="container">
    </footer>
  </body>
</html>